### ISSUE TITLE
about the future windows

### ISSUE THREAD

**Issue by ghghliu** [rajkiranjoshi/syndb-sim#9]
Hi, i have read your syNDB paper, it's quite enlightening，thank you.
I'm a little confused about the fellowing points about future window.
1.Is the future window stored in the ring buffer or other address.
2.In the syNDB pseudocode record part it seems the future p-record is stored in the precordArray, but in collection packet logic part, it seems only p-record in the ring buffer is collected. 
3.Does the p-records stored in future buffer be collected only when another trigger received during the collection.
4.If 3 is true, the figures in the paper(such as fig11), it seems that only one point satisfies queuing time 10000 ns, then what triggers the future data collection.
5.Where is the future buffer collection part in this simmulation.
Thanks again

**Comment by praveingk** [comment]
The handling of future buffer is also same as the history buffer, its collected along with the history buffer upon trigger condition.  Future buffer is an additional buffer designed in the same manner as the history buffer, but ideally smaller to handle just enough records for the collection time of history buffer.
Check out Section 7.3  for more clarity on this point: "Note that, SyNDB has a future buffer to store p-records once trigger condition is met. To support continuous recording of all future events, the
minimum duration the future buffer needs to capture is 260µs.".

**Comment by praveingk** [comment]
I forgot to mention that the simulator does not implement future buffer. Thanks for your queries. Hope its clear. Feel free to revert back in case of any questions

**Comment by ghghliu** [comment]
> I forgot to mention that the simulator does not implement future buffer. Thanks for your queries. Hope its clear. Feel free to revert back in case of any questions

Yes, it's clear, thanks for your explanations : )
